### ISSUE TITLE
AI AMP story generation

### ISSUE THREAD

**Issue by lucemia** [livingbio/web-stories-wp#2]
# Problem

在 gstudio 提供 API 將 Article 轉換成 AMP Story 

# Solution

(感覺這個 API 未來可以成為 AMP Story & GliaStudio 共用的格式 但先不管)

input: url
output: story format

## Story Format

- story
    - pages
        - headline
        - subtitle
        - background
            - url
            - type
            - focalX
            - focalY
            - title
        - elements (extension, not current used)
            - Chart, Form, Tables, … etc

**Comment by lucemia** [comment]
focalX, focalY 是素材該設定成種新的地方 ref: https://github.com/livingbio/gstudio/issues/1843

**Comment by banyh** [comment]
https://github.com/livingbio/web-stories-wp/blob/master/assets/src/edit-story/output/story.js#L82-L92
這個地方應該代表輸出格式

我先整理成一個表
https://docs.google.com/spreadsheets/d/1DPKrWx4svCsmKpohgkGJYSEEacC-_LtSzwXAJnxDbyc/edit?usp=sharing

**Comment by lucemia** [comment]
#8 完成以後，請 Bany 測試看看有什麼問題
- [ ] Test Run
